minimal_mistakes_skin    : "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Mohamad Ali Najia"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Mohamad Ali Najia"
description              : "Mohamad's Website"
url:                     //mnajia.github.io
disqus_shortname: mnajia
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title


# Owner/author information
owner:
  name:           Mohamad Ali Najia
  avatar:         mnajia.png
  bio:            This is my bio and a test of the web design. Lorum Ipsium. 
  location:       Boston, MA
  email:          test@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: mohamadnajia
  linkedin: mnajia3
  google_scholar: TBD
  github: mnajia
# Analytics and webmaster tools stuff goes here
google_analytics: UA-XXXXXXX-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Research
    url: /research/
  - title: Publications & Patents
    url: /publications/
  - title: Talks
    url: /talks/
  - title: Projects
    url: /projects/
  - title: CV
    url: /cv/
  - title: Personal
    url: /personal/
  - title: Blog
    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
